/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        background: '#0D0D0D',
        surface: '#1A1A1A',
        'surface-dim': '#1d100a',
        'surface-bright': '#46362e',
        'surface-container-lowest': '#170b06',
        'surface-container-low': '#261812',
        'surface-container': '#2b1c16',
        'surface-container-high': '#362720',
        'surface-container-highest': '#41312a',
        'surface-variant': '#333333',
        'on-surface': '#f8ddd2',
        'on-surface-variant': '#e2bfb0',
        'inverse-surface': '#f8ddd2',
        'inverse-on-surface': '#3d2d26',
        outline: '#333333',
        'outline-variant': '#333333',
        'surface-tint': '#ffb693',
        primary: '#ffb693',
        'on-primary': '#561f00',
        'primary-container': '#FF6B00',
        'on-primary-container': '#572000',
        'inverse-primary': '#a04100',
        secondary: '#708238',
        'on-secondary': '#293500',
        'secondary-container': '#3f4f08',
        'on-secondary-container': '#adc16f',
        tertiary: '#673AB7',
        'on-tertiary': '#3f008d',
        'tertiary-container': '#ac81ff',
        'on-tertiary-container': '#40008e',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#ffdbcc',
        'primary-fixed-dim': '#ffb693',
        'on-primary-fixed': '#351000',
        'on-primary-fixed-variant': '#7a3000',
        'secondary-fixed': '#d7ec95',
        'secondary-fixed-dim': '#bbcf7c',
        'on-secondary-fixed': '#161e00',
        'on-secondary-fixed-variant': '#3d4c05',
        'tertiary-fixed': '#ebddff',
        'tertiary-fixed-dim': '#d3bbff',
        'on-tertiary-fixed': '#250059',
        'on-tertiary-fixed-variant': '#5727a6',
        'on-background': '#f8ddd2',
        'grid-line': '#333333',
        'panel-bg': '#1A1A1A',
        'base-bg': '#0D0D0D',
        'accent-orange': '#FF6B00',
        'grid-border': '#333333',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '0px',
      },
      spacing: {
        gutter: '16px',
        margin: '24px',
        unit: '4px',
        grid_stroke: '1px',
      },
      fontFamily: {
        'display-lg': ['"Space Grotesk"', 'sans-serif'],
        'headline-lg': ['"Space Grotesk"', 'sans-serif'],
        'headline-md': ['"Space Grotesk"', 'sans-serif'],
        'headline-lg-mobile': ['"Space Grotesk"', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-mono': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-mono': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      transitionDuration: {
        DEFAULT: '50ms',
      },
    },
  },
  plugins: [],
};
